### ISSUE TITLE
哥们，如果我想要接虚拟机呢？

### ISSUE THREAD

**Issue by greenhandzdl** [FengQuanLi/ResnetGPT#13]
对于有的人来说，数据线常常会断。所以，我打算通过网络adb或者更加直接的是直接在系统上搭建虚拟机，但实际上虚拟机（安卓8）是特别占有内存，所以也就放弃了。
那么网络adb接手机的虚拟机安卓呢？不然时不时数据线将断了。

**Comment by 2563411574** [comment]
有点不太理解你的意思 在系统上搭虚拟机？
安卓模拟器本身就是一台虚拟机了

**Comment by greenhandzdl** [comment]
> 有点不太理解你的意思 在系统上搭虚拟机？
> 安卓模拟器本身就是一台虚拟机了

VM OS
我打算userland上切我的Debian，然后通过网络adb连接虚拟机（VM OS），然后将游戏本体下进去，就可以单个终端进行挂机了

**Comment by 2563411574** [comment]
或许可以 你可以尝试看看
