### ISSUE TITLE
想请问一下这个bug是怎么回事啊 为什么没有权限

### ISSUE THREAD

**Issue by KebingZ** [FengQuanLi/ResnetGPT#15]
![cfc08519539604d211244026d26c9a9](https://user-images.githubusercontent.com/71420444/106382683-352d4600-63fc-11eb-93dd-616f77ecee1e.png)

**Comment by 2563411574** [comment]
不支持安卓10 换手机或者用模拟器 
还有 建议提问前看看历史哦(´-ω-`)
记得关闭这个issues
