### ISSUE TITLE
关于安卓手机屏幕截图速度

### ISSUE THREAD

**Issue by dataaug** [FengQuanLi/ResnetGPT#18]
您好，很棒的工作，我最近也在做一些小游戏RL相关的代码，有一些代码问题想要请教一下。注意到您采用桌面截图的方式获得环境数据，这样是不是大概一秒才能完成一次截图呢？您是否有更好的截图建议呢？

**Comment by FengQuanLi** [comment]
截图的速度可以跟上scrcpy的渲染速度，估计30张/秒应该是没有问题。

**Comment by dataaug** [comment]
> 截图的速度可以跟上scrcpy的渲染速度，估计30张/秒应该是没有问题。

的确可以，之前用ADB的方式慢了点。感谢。
