### ISSUE TITLE
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by baltam** [FengQuanLi/ResnetGPT#2]
非常感谢dalao的开源代码，今天本来想尝试一下看看实际模型效果，根据up的步骤一步步走，结果在运行"训练数据截取_A.py"时报了一个错误
```python
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接
```
请问一下这是什么原因造成的呢，希望dalao能够抽空回答一下，不胜感激~

**Comment by FengQuanLi** [comment]
我猜测是因为pyminitouch模块会在你的手机没有安装minitouch的情况下，从github下载相应文件而被github拒绝导致。试着先手动安装minitouch可能会避免这个问题。

**Comment by baltam** [comment]
> 我猜测是因为pyminitouch模块会在你的手机没有安装minitouch的情况下，从github下载相应文件而被github拒绝导致。试着先手动安装minitouch可能会避免这个问题。

好的，谢谢up主！我刚刚退出又重新运行了一次，之前报的错误没了，现在报了另外一个错误
```python
2021-01-06 20:54:39.414 | INFO     | pyminitouch.utils:is_device_connected:56 - device Redmi K30 Pro Zoom Edition online
2021-01-06 20:54:39.416 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-01-06 20:54:41.418 | INFO     | pyminitouch.connection:__init__:89 - device 251e5331 bind to port 20751
2021-01-06 20:54:41.511 | INFO     | pyminitouch.connection:get_abi:35 - device 251e5331 is arm64-v8a
2021-01-06 20:54:41.565 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in 251e5331
2021-01-06 20:54:41.566 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s 251e5331 forward tcp:20751 localabstract:minitouch
2021-01-06 20:54:41.582 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b'20751\r\n'
2021-01-06 20:54:41.583 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s 251e5331 shell /data/local/tmp/minitouch
open: Permission denied
Unable to open device /dev/input/event7 for inspectionopen: Permission denied
Unable to open device /dev/input/event6 for inspectionopen: Permission denied
Unable to open device /dev/input/event5 for inspectionopen: Permission denied
Unable to open device /dev/input/event1 for inspectionopen: Permission denied
Unable to open device /dev/input/event0 for inspectionopen: Permission denied
Unable to open device /dev/input/event3 for inspectionopen: Permission denied
Unable to open device /dev/input/event4 for inspectionopen: Permission denied
Unable to open device /dev/input/event2 for inspectionUnable to find a suitable touch device
```
这是否意味着Android10无法使用minitouch呢，还是说需要开启root权限，up主之前有遇到过这个问题吗

**Comment by FengQuanLi** [comment]
在安卓调试桥下用shell命令更改权限为777

chmod 777 /data/local/tmp/minitouch
试试看行不行

**Comment by FengQuanLi** [comment]
> > 我猜测是因为pyminitouch模块会在你的手机没有安装minitouch的情况下，从github下载相应文件而被github拒绝导致。试着先手动安装minitouch可能会避免这个问题。
> 
> 好的，谢谢up主！我刚刚退出又重新运行了一次，之前报的错误没了，现在报了另外一个错误
> 
> ```python
> 2021-01-06 20:54:39.414 | INFO     | pyminitouch.utils:is_device_connected:56 - device Redmi K30 Pro Zoom Edition online
> 2021-01-06 20:54:39.416 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
> 2021-01-06 20:54:41.418 | INFO     | pyminitouch.connection:__init__:89 - device 251e5331 bind to port 20751
> 2021-01-06 20:54:41.511 | INFO     | pyminitouch.connection:get_abi:35 - device 251e5331 is arm64-v8a
> 2021-01-06 20:54:41.565 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in 251e5331
> 2021-01-06 20:54:41.566 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s 251e5331 forward tcp:20751 localabstract:minitouch
> 2021-01-06 20:54:41.582 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b'20751\r\n'
> 2021-01-06 20:54:41.583 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s 251e5331 shell /data/local/tmp/minitouch
> open: Permission denied
> Unable to open device /dev/input/event7 for inspectionopen: Permission denied
> Unable to open device /dev/input/event6 for inspectionopen: Permission denied
> Unable to open device /dev/input/event5 for inspectionopen: Permission denied
> Unable to open device /dev/input/event1 for inspectionopen: Permission denied
> Unable to open device /dev/input/event0 for inspectionopen: Permission denied
> Unable to open device /dev/input/event3 for inspectionopen: Permission denied
> Unable to open device /dev/input/event4 for inspectionopen: Permission denied
> Unable to open device /dev/input/event2 for inspectionUnable to find a suitable touch device
> ```
> 
> 这是否意味着Android10无法使用minitouch呢，还是说需要开启root权限，up主之前有遇到过这个问题吗

我没有试过Android10 并不清楚情况

**Comment by baltam** [comment]
> > > 我猜测是因为pyminitouch模块会在你的手机没有安装minitouch的情况下，从github下载相应文件而被github拒绝导致。试着先手动安装minitouch可能会避免这个问题。
> > 
> > 
> > 好的，谢谢up主！我刚刚退出又重新运行了一次，之前报的错误没了，现在报了另外一个错误
> > ```python
> > 2021-01-06 20:54:39.414 | INFO     | pyminitouch.utils:is_device_connected:56 - device Redmi K30 Pro Zoom Edition online
> > 2021-01-06 20:54:39.416 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
> > 2021-01-06 20:54:41.418 | INFO     | pyminitouch.connection:__init__:89 - device 251e5331 bind to port 20751
> > 2021-01-06 20:54:41.511 | INFO     | pyminitouch.connection:get_abi:35 - device 251e5331 is arm64-v8a
> > 2021-01-06 20:54:41.565 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in 251e5331
> > 2021-01-06 20:54:41.566 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s 251e5331 forward tcp:20751 localabstract:minitouch
> > 2021-01-06 20:54:41.582 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b'20751\r\n'
> > 2021-01-06 20:54:41.583 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s 251e5331 shell /data/local/tmp/minitouch
> > open: Permission denied
> > Unable to open device /dev/input/event7 for inspectionopen: Permission denied
> > Unable to open device /dev/input/event6 for inspectionopen: Permission denied
> > Unable to open device /dev/input/event5 for inspectionopen: Permission denied
> > Unable to open device /dev/input/event1 for inspectionopen: Permission denied
> > Unable to open device /dev/input/event0 for inspectionopen: Permission denied
> > Unable to open device /dev/input/event3 for inspectionopen: Permission denied
> > Unable to open device /dev/input/event4 for inspectionopen: Permission denied
> > Unable to open device /dev/input/event2 for inspectionUnable to find a suitable touch device
> > ```
> > 
> > 
> > 这是否意味着Android10无法使用minitouch呢，还是说需要开启root权限，up主之前有遇到过这个问题吗
> 
> 我没有试过Android10 并不清楚情况

好的，我试试。up主手机之前有root过么

**Comment by FengQuanLi** [comment]
没有root过手机

**Comment by baltam** [comment]
> 没有root过手机

好的，我知道什么原因了，刚刚去minitouch的repository看了看，目前还不支持Android 10，需要自己制作补丁，所以k30 pro暂时先不弄了。换了一台手机，没有root的mi 6可以正常运行了，感谢up主！

**Comment by jerryzhao173985** [comment]
> > 没有root过手机
> 
> 
> 
> 好的，我知道什么原因了，刚刚去minitouch的repository看了看，目前还不支持Android 10，需要自己制作补丁，所以k30 pro暂时先不弄了。换了一台手机，没有root的mi 6可以正常运行了，感谢up主！

小米6 能跑是能跑 可是小米6分辨率是1080*1960的 可是他的模型训练出的是1080*2160的 是不是得需要完全自己训练 他的模型键位被压缩了
