### ISSUE TITLE
英雄不怎么动

### ISSUE THREAD

**Issue by jinmeng123** [FengQuanLi/ResnetGPT#21]
大部分时间英雄是停止状态，偶尔来回转转，放个技能啥的？和你发的视频完全不一致，请问什么原因？

**Comment by 2563411574** [comment]
分辨率不同导致的 分辨率不一样会导致键位不同

**Comment by FengQuanLi** [comment]
一、检查打印输出的动作是否与角色动作一致，如楼上所说分辨率不一样会导致键位不同
二、如果一致，检查AI每次判断时间是否小于0.22秒
三、如果时间小于0.22秒，看看训练好的模型是否加载。
四、模型本身不完善，或者游戏更新
五、训练数据不足

**Comment by 2563411574** [comment]
问题如果已解决请关闭此issues

**Comment by jinmeng123** [comment]
每次打印出来的延时最长时间是0.06左右，模型家没有加载好如何判断？

**Comment by jinmeng123** [comment]
![捕获](https://user-images.githubusercontent.com/10309716/108375060-865d7800-71f9-11eb-85aa-51671ebaaf91.PNG)
