### ISSUE TITLE
你好作者，我有个脑洞大开的想法

### ISSUE THREAD

**Issue by qiuqiu3** [FengQuanLi/ResnetGPT#22]
这套程序是否可以实现自动抢各大平台发售的茅台酒。比如可以打开苏宁的 App、自动预约、到时间自己点抢购按钮，出现的弹出框可以自动关闭等等，我现在用 Android 的辅助服务可以实现，但是灵活性不强，如果真的可以像人类这样操作的话可以节省很多修性代码的工作量。

**Comment by 2563411574** [comment]
您好 这可真是脑洞大开......
这只需要python就可以实现 要机器人干嘛？
设置定时任务 然后挂到服务器上面去即可
Github上面有一堆这种源码
可以自行搜索
问题如果已解决请关闭此issue
