### ISSUE TITLE
训练效率

### ISSUE THREAD

**Issue by workofart** [FengQuanLi/ResnetGPT#25]
你好，看到你这个项目让我还挺惊喜的，因为2年前我也做了一个类似的项目是训练一个[AI去玩荒野乱斗](https://github.com/workofart/brawlstars-ai)。不过最后因为训练效率太低（主要是因为没有一个类似围棋或者象棋的模拟器）就搁浅了。

请问你对于这种手游（尤其是没有开源的后端API）训练效率有什么好的提升方法？

**Comment by FengQuanLi** [comment]
你的项目非常不错，很多方面比我做得好。
监督学习需要用的大量的训练数据，而强化学习需要大量的训练次数，对于没有官方提供后端API的手游，这些都是难以直接实现的。
我的解决思路是，针对目标手游做一个本地化的游戏，用深度强化学习如(PPO)预训练一个模型，再用在手游上做微调。

**Comment by workofart** [comment]
嗯，我觉得你提的方法确实是一个不错的思路，而且一开始做的这个本地化的游戏应该是一个很笼统/简约的MOBA游戏，训练完模型后还在其他类似手游上进行微调。

我对于这种强化学习应用项目总结出来的经验是，训练模型和搭建一个可以重复利用和可靠的pipeline一样重要。甚至说，如果没有一个好的pipeline，我们developer的debug的效率就大大降低了，天天原地打转。

还有就是我发现如果没有一个好的后端API，花在perception上面的时间远大于planning上面的时间。本来我是想做一个强化学习的项目，最后被迫花60%的时间在做计算机视觉 :joy:

**Comment by FengQuanLi** [comment]
是的，模型如同大脑没有眼睛和手什么也干不了。
非常感谢你分享的经验。

**Comment by workofart** [comment]
恩恩，也感谢你开源的这个项目，给了我一些启发。:smile:
