### ISSUE TITLE
想问一下，训练数据如何标注

### ISSUE THREAD

**Issue by zineos** [FengQuanLi/ResnetGPT#3]

**Comment by FengQuanLi** [comment]
当用按键控制游戏角色时就会自动生成训练数据。
训练数据包括两部分：一是图片，二是每张图片对应的操作（由图片同目录的json文件记录）。
这个记录的操作就是一种标注。

**Comment by zineos** [comment]
希望把生成训练数据方法共享出来，这样大家都可以贡献数据集

**Comment by virtualpeer** [comment]
是在哪个代码里实现这个功能的？ 没看到，是不是相当于自动截屏功能吗？

**Comment by wanghaisheng** [comment]
@FengQuanLi 
感觉把训练详细说说 是不是大家可以多贡献一些数据

**Comment by yeyupiaoling** [comment]
>@FengQuanLi
感觉把训练详细说说 是不是大家可以多贡献一些数据

对啊，我也想问，我们是否都可以贡献数据，集成一个超大数据集

**Comment by 2563411574** [comment]
> @FengQuanLi
> 感觉把训练详细说说 是不是大家可以多贡献一些数据

训练方法的文档在QQ群168899181的群文件里面 加群获取

**Comment by 2563411574** [comment]
> > @FengQuanLi
> > 感觉把训练详细说说 是不是大家可以多贡献一些数据
> 
> 对啊，我也想问，我们是否都可以贡献数据，集成一个超大数据集

训练方法的文档在QQ群168899181的群文件里面 加群获取
