### ISSUE TITLE
AttributeError: module 'torchtext.data' has no attribute 'Iterator'

### ISSUE THREAD

**Issue by cccisbug** [FengQuanLi/ResnetGPT#30]
C:\Users\Administrator>python D:\ai\ResnetGPT-master\训练数据截取_A.py
Traceback (most recent call last):
  File "D:\ai\ResnetGPT-master\训练数据截取_A.py", line 5, in <module>
    from Batch import create_masks
  File "D:\ai\ResnetGPT-master\Batch.py", line 32, in <module>
    class MyIterator(data.Iterator):
AttributeError: module 'torchtext.data' has no attribute 'Iterator'

使用miniconda安装的环境，python3.7 ,torchtext-0.9.1,torchvision 等，请问这个报错是什么原因？库的版本问题么

**Comment by FengQuanLi** [comment]
把用到torchtex模块的类和方法注释掉就好了，torchtex这里实际上是没用的。

**Comment by cccisbug** [comment]
> 把用到torchtex模块的类和方法注释掉就好了，torchtex这里实际上是没用的。

好的，谢谢~
