### ISSUE TITLE
AI玩王者数据分享汇总

### ISSUE THREAD

**Issue by FengQuanLi** [FengQuanLi/ResnetGPT#34]
AI玩王者数据汇总，开贴汇集数据。
如果您想分享训练数据 回复包含数据的网盘地址和密码即可。
这里先分享我的部分数据
局数：约150局（每局数据大小几百兆到2G不等）
等级：青铜人机
英雄：后裔
是否预处理 ：含图片且有预处理

百度网盘
链接： https://pan.baidu.com/s/19fG_1jK4xBThtmrCg-u4rg 
提取码：eytn

**Comment by XXGUI** [comment]
> AI玩王者数据汇总，开贴汇集数据。


分享出来的这些数据我们应该怎么使用，建议出教程，按照主页描述的操作我这边是操作失败的

**Comment by FengQuanLi** [comment]
> 分享出来的这些数据我们应该怎么用，建议出教程，按照主页描述的操作我这个是操作失败的



可以加QQ群：
714228242
群里有教程

**Comment by XXGUI** [comment]
> 714228242

我申请了啊，都三天了也没见有人同意。。。。。
