### ISSUE TITLE
启动出现torch.cuda.is_available()=False等问题的解决方案

### ISSUE THREAD

**Issue by XXGUI** [FengQuanLi/ResnetGPT#38]
如果是cuda启动不了可以尝试吧代码里的 “ cuda(device) ” 换成  “ cpu() ” 
需要更改的文件大概有三个，改完运行就可以了 ( ❛⃘ ∨ ❜⃘⃘ )੭⁂

修改完之后可能造成无法自动启动“ scrcpy ”，没启动scrcpy那就先手动启动scrcpy在执行“训练数据截取_A.py”

项目运行环境不一定并没有主页描述的那么高，cpu-i3-8100显卡英达伟1G都跑得起来ヾ(Ő∀Ő๑)ﾉ

**Comment by FengQuanLi** [comment]
训练的时候我是按0.22秒截取一张图片处理的。我的gtx1660处理一张越0.1秒。只要能在0.22秒处理完都是可以的。
如果大于这个时间则需要重新训练。
