### ISSUE TITLE
这个ai可以帮我上王者吗

### ISSUE THREAD

**Issue by liian2018** [FengQuanLi/ResnetGPT#6]

**Comment by zephms** [comment]
希望可以

**Comment by sunxiaolong321** [comment]
我感觉行

**Comment by sunxiaolong321** [comment]
我感觉靠谱

**Comment by sunxiaolong321** [comment]
别说王者了，都可以带你打职业联赛

**Comment by ruixule** [comment]
> 别说王者了，都可以带你打职业联赛

你把程序部署好了吗

**Comment by 2563411574** [comment]
> 别说王者了，都可以带你打职业联赛

这个训练数据非常少 只有几百场而已 如果要打王者起码上千w场才可以达得到
假设每场需要20分钟 那么1w场就需要3333天
也就是9年 日夜不停的打 如果没有大家提供足够的训练数据 也没有人维护项目 那么这个是永远不可能的

**Comment by cexll** [comment]
> > 别说王者了，都可以带你打职业联赛
> 
> 这个训练数据非常少 只有几百场而已 如果要打王者起码上千w场才可以达得到
> 假设每场需要20分钟 那么1w场就需要3333天
> 也就是9年 日夜不停的打 如果没有大家提供足够的训练数据 也没有人维护项目 那么这个是永远不可能的

你这个只是在单台,如果砸钱 靠多台 时间会缩减很多

**Comment by Dustyposa** [comment]
> > 别说王者了，都可以带你打职业联赛
> 
> 这个训练数据非常少 只有几百场而已 如果要打王者起码上千w场才可以达得到
> 假设每场需要20分钟 那么1w场就需要3333天
> 也就是9年 日夜不停的打 如果没有大家提供足够的训练数据 也没有人维护项目 那么这个是永远不可能的

不用砸钱，换个训练方式，不需要实际玩。只需要实际的数据，那么可以加速的。

**Comment by heartInsert** [comment]
你干脆直接问能不能帮你年入百万算了
