### ISSUE TITLE
您好，请问能不能展示一下这个model的主体神经网络涉及的论文呢？

### ISSUE THREAD

**Issue by curryJ** [FengQuanLi/ResnetGPT#7]
谢谢

**Comment by FengQuanLi** [comment]
我的模型是resnet101接一个transformer的解码部分，并没有专门的论文。
我是受到了看图说话的相关源码的启发——既然可以看图说话（图片到文字），那么这些文字可以是针对游戏的操作命令。
大概思路就是这样。
我这里把lstm替换为transformer的解码部分
